### PR TITLE
Expended functionality

### PR DESCRIPTION
**Pull request by abbaye**
```
ADD support of percent string format (P to P6)
BUG FIX When popup closed the window do not freeze
Little desing update un popup
Add PopupClosed event
Add support of Undolimit
Add functionality ADD/REMOVE popup (Enter Key when CanShowAddPanel = true)
Add support of numeric value (Stringformat N to N6)
Validate MinimumValue / MaximumValue dependency properties
Validate StringFormat dependency property
Add support of Undo/Redo
Add Copy/Paste
```

### CODE REVIEW

**Comment by MrZander** [comment]
These modification cause a lot of problems.  Not entirely sure what is going on in RemoveRightMostDigit() now, but it definitely doesn't work properly since I tested this branch.

**Comment by abbaye** [comment]
Thank for e-mail

I will check tais tais week-end en post an update.

Can you give me more detail this bug ?

Regards

**Comment by mtusk** [comment]
This feels like a complete re-write that fulfills a need this control wasn't intended to fill.
- <kbd>Backspace</kbd> sometimes clears the value instead of removing the right-most digit
- `Minimum` don't appear to have any impact
- The add/remove popup is an interesting interaction that I could see being useful but I feel is scope creep for the goal of this project

**Comment by abbaye** [comment]
Humm this spécial it Word good for me...

I think is the localisation??. I use french canadien and i have developped
with this. I will put my system in english US for testing

Le 13 sept. 2016 12:22 AM, "Adam Anderson" <notifications@github.com> a
écrit :

**Comment by abbaye** [comment]
Haaaa is not the updated code !

check my Fork : https://github.com/abbaye/wpf-currency-textbox
you can test package on nuget  https://www.nuget.org/packages/CurrencyTextBox/

"I think" it's work fine :)

**Pull request closed without merging**
